### PR TITLE
Classes - print movie description

### PR DESCRIPTION
**Pull request by Rahulkug**
## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [x] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [x] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [x] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [x] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [x] There are at least 2 test cases
    - [x] There is at least 1 test case that is different from the sample test cases

### CODE REVIEW

**Comment by LVSsandeepVarma** [comment]
@Rahulkug  please use camelcase for naming variables

**Review by LVSsandeepVarma — APPROVED** [review]

**Comment by sailesh-ramayanam** [comment]
@LVSsandeepVarma 
1. The objects should have the following variables: ~integer~ lengthInMinutes, ~integer~ numCharacters, ~string~ language 
2. The class ~Each object~ should ~also~ have a run method
3. which prints out: "This is a <language> movie with <numCharacters> and is <lengthInMinutes> minutes long." (correct this line even in the output format.

**Comment by LVSsandeepVarma** [comment]
> 

@sailesh-ramayanam   shall I replace this line  "This is a movie with and is minutes long."  with    "This is a `language` movie with `numCharacters` characters and is `lengthInMinutes` minutes long."

**Comment by sailesh-ramayanam** [comment]
@LVSsandeepVarma The template is still missing.

**Comment by LVSsandeepVarma** [comment]
@sailesh-ramayanam  updated the template

**Review by sailesh-ramayanam — APPROVED** [review]

**Pull request merged**
