### PR TITLE
Recursion - Sum of first n

### PR DESCRIPTION
**Pull request by DevratAgarwal**
## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [x] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [x] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [x] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [x] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [x] There are at least 2 test cases
    - [x] There is at least 1 test case that is different from the sample test cases

### CODE REVIEW

**Comment by vinthaivendhan10x** [comment]
@rpapavan97 kindly Review

**Review by rpapavan97 — CHANGES_REQUESTED** [review]
@DevratAgarwal, please console the numbers in the function itself, dont modify the template given as the students will code the logic only in the given template function

**Comment by rpapavan97** [comment]
@DevratAgarwal, we can write the logic like this

```
function sumOfFirstN(n){
	//Implement this function
	let recursiveSum = 0
	if (n === 1) {
		recursiveSum = 1;
	}
	else {
		recursiveSum = n + sumOfFirstN(n - 1);
	}
	console.log(n, recursiveSum)
	return recursiveSum
}
```

**Comment by DevratAgarwal** [comment]
@rpapavan97 done

**Comment by vinthaivendhan10x** [comment]
@rpapavan97 kindly Review

**Review by rpapavan97 — APPROVED** [review]

**Comment by vinthaivendhan10x** [comment]
@sailesh-ramayanam kindly Review

**Review by sailesh-ramayanam — APPROVED** [review]

**Pull request merged**
