### PR TITLE
Arrays - right to left diagonal

### PR DESCRIPTION
**Pull request by DevratAgarwal**
## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [x] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [x] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [x] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [x] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [x] There are at least 2 test cases
    - [x] There is at least 1 test case that is different from the sample test cases

### CODE REVIEW

**Comment by sailesh-ramayanam** [comment]
@rpapavan97 
1. Please add explanation for the sample test case
2. Please rename `lst` to `matrix` in the template and also other variables like `val` etc.

**Comment by rpapavan97** [comment]
@sailesh-ramayanam, updated the explanation section and modified the template variables in spoj widget

**Comment by rpapavan97** [comment]
@DevratAgarwal, please add ".js" file extension in the file name

**Comment by DevratAgarwal** [comment]
@rpapavan97 done

**Review by rpapavan97 — APPROVED** [review]

**Review by sailesh-ramayanam — APPROVED** [review]

**Pull request merged**
