### PR TITLE
Array - transpose matrix

### PR DESCRIPTION
**Pull request by DevratAgarwal**
## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [ ] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [ ] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [ ] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [ ] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [ ] There are at least 2 test cases
    - [ ] There is at least 1 test case that is different from the sample test cases

### CODE REVIEW

**Comment by LVSsandeepVarma** [comment]
@DevratAgarwal  I have  updated the template code can you please make changes accordingly

**Review by LVSsandeepVarma — APPROVED** [review]

**Comment by sailesh-ramayanam** [comment]
@LVSsandeepVarma 
Output format says `p` lines. It should say `n` lines containing `m` integers each.

**Comment by LVSsandeepVarma** [comment]
> 

@sailesh-ramayanam , replaced `p' with `n` in the output

**Comment by DevratAgarwal** [comment]
@LVSsandeepVarma @sailesh-ramayanam changes are addressed

**Comment by prathyusha10x** [comment]
@sailesh-ramayanam @LVSsandeepVarma please review the updated code and approve the PR by tomorrow EOD

**Review by sailesh-ramayanam — APPROVED** [review]

**Pull request merged**
