### PR TITLE
Functions - Brick Volume

### PR DESCRIPTION
**Pull request by Abduliitr**
## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [x] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [x] Author
    - [x] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [x] Author
    - [x] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [x] Author
    - [x] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [x] There are at least 2 test cases
    - [x] There is at least 1 test case that is different from the sample test cases

### CODE REVIEW

**Comment by Abduliitr** [comment]
The current solution will fail one test case on sphere engine, because - `In python round(0.5) gives 0, however in js, round(0.5) gives 1.`

So the template code below needs to be modified for js i think to keep using that test-case, or else we may remove that test.

```
function calculate_price(volume, price=0.00005){
	return Math.round(volume*price)
}
```

**Comment by LVSsandeepVarma** [comment]
@Abduliitr , so in this problem  if the volume*price value is 0.5 then result should be 0 and if the volume * price value is 0.6 it should be 1 right ?

**Comment by Abduliitr** [comment]
Yes.

**Comment by LVSsandeepVarma** [comment]
> @Abduliitr , so in this problem if the volume*price value is 0.5 then result should be 0 and if the volume * price value is 0.6 it should be 1 right ?

@sailesh-ramayanam   shall I change the output for that test case ?

**Comment by Abduliitr** [comment]
> > @Abduliitr , so in this problem if the volume*price value is 0.5 then result should be 0 and if the volume * price value is 0.6 it should be 1 right ?
> 
> @sailesh-ramayanam shall I change the output for that test case ?

Changing the output of the test-case will create an issue, if we have some python widget for the same problem.

**Review by rpapavan97 — CHANGES_REQUESTED** [review]
Code is giving 85.71% accepted

For testcase
1
10 10
The output given in sphere engine is 0, but here we are getting 1, 
totalVolume for this testcase will be 10000 and the totalPrice will be (Math.round(0.5)) which will be 1 in JS, 
as this problem is used for python before if we use round(0.5) it will give 0 in that case and accepted 100%,
need some assistance in changing the testcase here

**Comment by LVSsandeepVarma** [comment]
@sailesh-ramayanam   I have updated the test cases , so that all the outputs are floor values
so in the problem's sample  example for output `Single line returning the cost. This will be integer rounded to the closest integer.` in place of this shall I replace it with `Single line returning the cost. This value be the floored  to nearest integer `

**Comment by sailesh-ramayanam** [comment]
@LVSsandeepVarma In this case, I guess no need to create a new problem. Just editing the problem should be sufficient. For Python widgets also, it will be floor. `Single line returning the cost. If it is a float value, then return its floor. For e.g. if the cost is 20.7, you must return 20.`

**Comment by Abduliitr** [comment]
> @sailesh-ramayanam ok, I have updated the testcases according to the floor values

Also please update the template for `Math.floor`

I have updated it in the PR already.

**Comment by LVSsandeepVarma** [comment]
@Abduliitr  updated in the template

**Review by sailesh-ramayanam — APPROVED** [review]

**Review by shivateja1729 — APPROVED** [review]

**Review by LVSsandeepVarma — APPROVED** [review]

**Review by rpapavan97 — APPROVED** [review]

**Review by rpapavan97 — COMMENTED** [review]
Just a suggestion @LVSsandeepVarma , in problem description in Output 
Instead of "Single line returning the cost. This will be integer rounded to the closest integer."
we can write "Single line returning the cost. This will be the integer rounded to the floor value."

**Pull request merged**
