### PR TITLE
recursion - factorial recursive

### PR DESCRIPTION
**Pull request by Devjyoti29**
Hi,

With my solution 1 test case is failing. I think its because of large number as input leading to memory overflow.
 Kindly check and approve.

Regards,
Devjyoti Rakshit

### CODE REVIEW

**Comment by LVSsandeepVarma** [comment]
@Devjyoti29  ok will update you on it

**Review by LVSsandeepVarma — APPROVED** [review]

**Comment by LVSsandeepVarma** [comment]
@DevratAgarwal  updated the testcases

**Comment by DevratAgarwal** [comment]
@LVSsandeepVarma its @Devjyoti29

**Comment by LVSsandeepVarma** [comment]
> @LVSsandeepVarma its @Devjyoti29

Ok

**Comment by Devjyoti29** [comment]
> @Devjyoti29 updated the testcases

Ok

**Comment by vinthaivendhan10x** [comment]
@sailesh-ramayanam kindly Review

**Review by sailesh-ramayanam — APPROVED** [review]

**Pull request merged**
