### PR TITLE
Arithmetics - Square Sum

### PR DESCRIPTION
**Pull request by Abduliitr**
## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [x] Author
    - [ ] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [x] Author
    - [ ] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [x] Author
    - [ ] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [x] Author
    - [ ] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [ ] There are at least 2 test cases
    - [ ] There is at least 1 test case that is different from the sample test cases

### CODE REVIEW

**Comment by Abduliitr** [comment]
Printing the output without `parseInt` is also passing 100% tests currently. I think we should add a test-case, which will pass only if the output is printing with `parseInt`.

**Comment by LVSsandeepVarma** [comment]
@Abduliitr , I don't think there are any numbers for which  the output will be in decimal point for this problem, 
@sailesh-ramayanam  please suggest  how to proceed with this problem

**Comment by sailesh-ramayanam** [comment]
@Abduliitr @LVSsandeepVarma Sum of squares of first `n` natural numbers will always be an integers. So, no need of explicit conversion to `int`.

**Comment by Abduliitr** [comment]
> @Abduliitr @LVSsandeepVarma Sum of squares of first `n` natural numbers will always be an integer. So, no need of explicit conversion to `int`.

Removed parseInt.

**Review by LVSsandeepVarma — APPROVED** [review]

**Review by sailesh-ramayanam — APPROVED** [review]

**Pull request merged**
